import { defineConfig } from "tsdown";

export default defineConfig([
    {
        entry: { types: "src/types.ts" },
        format: ["esm"],
        dts: true,
        outDir: "dist",
    },
    {
        entry: ["src/index.ts"],
        format: ["esm", "cjs"],
        dts: true,
        sourcemap: true,
        minify: false,
        target: "es2022",
        outDir: "dist",
    },
    {
        entry: ["src/text-metrics.ts"],
        format: ["esm", "cjs"],
        dts: true,
        sourcemap: false,
        minify: false,
        target: "es2020",
        outDir: "dist/text-metrics",
    },
    {
        entry: ["src/node/index.ts"],
        format: ["esm", "cjs"],
        dts: true,
        sourcemap: true,
        deps: { neverBundle: ["inspector", "fs", "path", "node:crypto", "node:events", "node:fs", "node:net", "node:path", "node:util"] },
        minify: false,
        target: "es2022",
        outDir: "dist/node",
    },
    {
        entry: ["src/web/index.ts"],
        format: ["esm"],
        dts: true,
        sourcemap: true,
        deps: { neverBundle: ["vue"] },
        minify: false,
        target: "es2020",
        outDir: "dist/web",
    },
    {
        entry: ["src/web/property.ts"],
        format: ["esm"],
        dts: true,
        sourcemap: true,
        deps: {
            neverBundle: ["vue"],
        },
        minify: false,
        target: "es2020",
        outDir: "dist/web",
    },
    {
        entry: ["src/web/ui/index.ts"],
        format: ["esm"],
        dts: true,
        sourcemap: true,
        deps: {
            neverBundle: ["vue"],
        },
        minify: false,
        target: "es2020",
        outDir: "dist/web/ui",
    },
]);
